[workspace]
authors = ["Duncan McBain <git@mail.duncanmcba.in>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "dfs-tracer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025100916,<0.26"
